Vote Prediction: org.jboss.as.quickstarts.greeter.web.AdminController Class Reference
org.jboss.as.quickstarts.greeter.web.AdminController Class Reference
This controller is used change role of the users present in the database.
Public Member Functions
void change ()
This function calls the getForUsername and changeUserRole to change the role of the users in the database.
String getName ()
This function gets the name attribute from the admin_page.XHTML page.
void setName (String name)
This function sets the name attribute to the admin_page.XHTML page.
int getRole ()
This function gets the role attribute from the admin_page.XHTML page.
void setRole (int role)
This function sets the role attribute to the admin_page.XHTML page.
String getGreeting ()
This function gets the greeting attribute from the admin_page.XHTML page.
Private Attributes
User newUser = new User()
UserDao userDao
String name
int role
String greeting
Detailed Description
This controller is used change role of the users present in the database.
Author
MIR
Definition at line 20 of file AdminController.java.
Member Function Documentation
change()
void org.jboss.as.quickstarts.greeter.web.AdminController.change ()
This function calls the getForUsername and changeUserRole to change the role of the users in the database.
Definition at line 38 of file AdminController.java.
References org.jboss.as.quickstarts.greeter.domain.UserDao.changeUserRole(), org.jboss.as.quickstarts.greeter.domain.UserDao.getForUsername(), org.jboss.as.quickstarts.greeter.domain.User.getRole(), org.jboss.as.quickstarts.greeter.web.AdminController.getRole(), and org.jboss.as.quickstarts.greeter.domain.User.setRole().
getGreeting()
String org.jboss.as.quickstarts.greeter.web.AdminController.getGreeting ()
This function gets the greeting attribute from the admin_page.XHTML page.
Definition at line 80 of file AdminController.java.
References org.jboss.as.quickstarts.greeter.web.AdminController.greeting.
getName()
String org.jboss.as.quickstarts.greeter.web.AdminController.getName ()
This function gets the name attribute from the admin_page.XHTML page.
Definition at line 52 of file AdminController.java.
References org.jboss.as.quickstarts.greeter.web.AdminController.name.
getRole()
int org.jboss.as.quickstarts.greeter.web.AdminController.getRole ()
This function gets the role attribute from the admin_page.XHTML page.
Definition at line 66 of file AdminController.java.
References org.jboss.as.quickstarts.greeter.web.AdminController.role.
Referenced by org.jboss.as.quickstarts.greeter.web.AdminController.change().
setName()
void org.jboss.as.quickstarts.greeter.web.AdminController.setName (String name)
This function sets the name attribute to the admin_page.XHTML page.
Definition at line 59 of file AdminController.java.
References org.jboss.as.quickstarts.greeter.web.AdminController.name.
setRole()
void org.jboss.as.quickstarts.greeter.web.AdminController.setRole (int role)
This function sets the role attribute to the admin_page.XHTML page.
Definition at line 73 of file AdminController.java.
References org.jboss.as.quickstarts.greeter.web.AdminController.role.
Member Data Documentation
greeting
String org.jboss.as.quickstarts.greeter.web.AdminController.greeting private
Definition at line 33 of file AdminController.java.
Referenced by org.jboss.as.quickstarts.greeter.web.AdminController.getGreeting().
name
String org.jboss.as.quickstarts.greeter.web.AdminController.name private
Definition at line 29 of file AdminController.java.
Referenced by org.jboss.as.quickstarts.greeter.web.AdminController.getName(), and org.jboss.as.quickstarts.greeter.web.AdminController.setName().
newUser
User org.jboss.as.quickstarts.greeter.web.AdminController.newUser = new User() private
Definition at line 24 of file AdminController.java.
role
int org.jboss.as.quickstarts.greeter.web.AdminController.role private
Definition at line 31 of file AdminController.java.
Referenced by org.jboss.as.quickstarts.greeter.web.AdminController.getRole(), and org.jboss.as.quickstarts.greeter.web.AdminController.setRole().
userDao
UserDao org.jboss.as.quickstarts.greeter.web.AdminController.userDao private
Definition at line 27 of file AdminController.java.
The documentation for this class was generated from the following file:
src/main/java/org/jboss/as/quickstarts/greeter/web/AdminController.java