Vote Prediction: org.jboss.as.quickstarts.greeter.domain.User Class Reference
org.jboss.as.quickstarts.greeter.domain.User Class Reference
This class maps to the Users table in the database.
Public Member Functions
Long getId ()
String getUsername ()
void setUsername (String username)
int getRole ()
void setRole (int role)
String getPassword ()
void setPassword (String password)
Private Attributes
Long id
String username
int role
String password
Detailed Description
This class maps to the Users table in the database.
Author
MIR
Definition at line 33 of file User.java.
Member Function Documentation
getId()
Long org.jboss.as.quickstarts.greeter.domain.User.getId ()
Definition at line 46 of file User.java.
getPassword()
String org.jboss.as.quickstarts.greeter.domain.User.getPassword ()
Definition at line 66 of file User.java.
Referenced by org.jboss.as.quickstarts.greeter.web.GreetController.greet().
getRole()
int org.jboss.as.quickstarts.greeter.domain.User.getRole ()
Definition at line 58 of file User.java.
Referenced by org.jboss.as.quickstarts.greeter.web.AdminController.change(), org.jboss.as.quickstarts.greeter.domain.EJBUserDao.changeUserRole(), org.jboss.as.quickstarts.greeter.domain.ManagedBeanUserDao.changeUserRole(), and org.jboss.as.quickstarts.greeter.web.GreetController.greet().
getUsername()
String org.jboss.as.quickstarts.greeter.domain.User.getUsername ()
Definition at line 50 of file User.java.
Referenced by org.jboss.as.quickstarts.greeter.domain.EJBUserDao.changeUserRole(), org.jboss.as.quickstarts.greeter.domain.ManagedBeanUserDao.changeUserRole(), and org.jboss.as.quickstarts.greeter.web.GreetController.greet().
setPassword()
void org.jboss.as.quickstarts.greeter.domain.User.setPassword (String password)
Definition at line 70 of file User.java.
setRole()
void org.jboss.as.quickstarts.greeter.domain.User.setRole (int role)
Definition at line 62 of file User.java.
Referenced by org.jboss.as.quickstarts.greeter.web.AdminController.change().
setUsername()
void org.jboss.as.quickstarts.greeter.domain.User.setUsername (String username)
Definition at line 54 of file User.java.
Member Data Documentation
id
Long org.jboss.as.quickstarts.greeter.domain.User.id private
Definition at line 37 of file User.java.
password
String org.jboss.as.quickstarts.greeter.domain.User.password private
Definition at line 44 of file User.java.
role
int org.jboss.as.quickstarts.greeter.domain.User.role private
Definition at line 42 of file User.java.
username
String org.jboss.as.quickstarts.greeter.domain.User.username private
Definition at line 40 of file User.java.
The documentation for this class was generated from the following file:
src/main/java/org/jboss/as/quickstarts/greeter/domain/User.java