Vote Prediction: org.jboss.as.quickstarts.greeter.domain.MainCluster Class Reference
org.jboss.as.quickstarts.greeter.domain.MainCluster Class Reference
It is a Serializable class used to map the clusters in the database.
Public Member Functions
MainCluster ()
final List< ClusterModel > getData ()
final void setData (List< ClusterModel > objct)
Private Attributes
List< ClusterModel > objct
Static Private Attributes
static final long serialVersionUID = 1L
Detailed Description
It is a Serializable class used to map the clusters in the database.
Author
MIR
Definition at line 11 of file MainCluster.java.
Constructor & Destructor Documentation
MainCluster()
org.jboss.as.quickstarts.greeter.domain.MainCluster.MainCluster ()
Definition at line 17 of file MainCluster.java.
Member Function Documentation
getData()
final List<ClusterModel> org.jboss.as.quickstarts.greeter.domain.MainCluster.getData ()
Definition at line 23 of file MainCluster.java.
References org.jboss.as.quickstarts.greeter.domain.MainCluster.objct.
Referenced by org.jboss.as.quickstarts.greeter.domain.ManagedBeanModelDao.calcAccuracy(), and org.jboss.as.quickstarts.greeter.domain.ManagedBeanModelDao.predictModel().
setData()
final void org.jboss.as.quickstarts.greeter.domain.MainCluster.setData (List< ClusterModel > objct)
Definition at line 29 of file MainCluster.java.
References org.jboss.as.quickstarts.greeter.domain.MainCluster.objct.
Referenced by org.jboss.as.quickstarts.greeter.domain.ManagedBeanModelDao.calcAccuracy(), and org.jboss.as.quickstarts.greeter.domain.ManagedBeanModelDao.saveModel().
Member Data Documentation
objct
List<ClusterModel> org.jboss.as.quickstarts.greeter.domain.MainCluster.objct private
Definition at line 15 of file MainCluster.java.
Referenced by org.jboss.as.quickstarts.greeter.domain.MainCluster.getData(), and org.jboss.as.quickstarts.greeter.domain.MainCluster.setData().
serialVersionUID
final long org.jboss.as.quickstarts.greeter.domain.MainCluster.serialVersionUID = 1L static private
Definition at line 13 of file MainCluster.java.
The documentation for this class was generated from the following file:
src/main/java/org/jboss/as/quickstarts/greeter/domain/MainCluster.java