Vote Prediction: org.jboss.as.quickstarts.greeter.web.DeveloperController Class Reference
org.jboss.as.quickstarts.greeter.web.DeveloperController Class Reference
Public Member Functions
void trainmodel ()
This functions calls the trainModel function to create the clusters using Kmeans algorithm.
void savemodel ()
This function calls the saveModel function in the bean to save the clusters in the database.
void calcacc ()
This function calls the calcAccuracy in the bean to calculate the accuracy of the algorithm.
String getInputfilepath ()
This function gets the input file path in HDFS from the developer_page.xhtml.
void setInputfilepath (String inputfilepath)
String getModelfilepath ()
This function gets the model file path in HDFS from the developer_page.xhtml.
void setModelfilepath (String modelfilepath)
String getOutputfilepath ()
This function gets the output file path in HDFS from the developer_page.xhtml.
void setOutputfilepath (String outputfilepath)
String getModelclassname ()
This function gets the model class name in the database from the developer_page.xhtml.
void setModelclassname (String modelclassname)
String getGreeting ()
This function gets the greeting attribute from the developer_page.XHTML page.
Private Attributes
ModelDao modelDao
String inputfilepath
String modelclassname
String outputfilepath
String modelfilepath
String greeting
Detailed Description
Definition at line 33 of file DeveloperController.java.
Member Function Documentation
calcacc()
void org.jboss.as.quickstarts.greeter.web.DeveloperController.calcacc ()
This function calls the calcAccuracy in the bean to calculate the accuracy of the algorithm.
Definition at line 74 of file DeveloperController.java.
References org.jboss.as.quickstarts.greeter.domain.ModelDao.calcAccuracy(), org.jboss.as.quickstarts.greeter.web.DeveloperController.getModelclassname(), and org.jboss.as.quickstarts.greeter.web.DeveloperController.getModelfilepath().
getGreeting()
String org.jboss.as.quickstarts.greeter.web.DeveloperController.getGreeting ()
This function gets the greeting attribute from the developer_page.XHTML page.
Definition at line 153 of file DeveloperController.java.
References org.jboss.as.quickstarts.greeter.web.DeveloperController.greeting.
getInputfilepath()
String org.jboss.as.quickstarts.greeter.web.DeveloperController.getInputfilepath ()
This function gets the input file path in HDFS from the developer_page.xhtml.
Returns
the input file path in string format.
Definition at line 90 of file DeveloperController.java.
References org.jboss.as.quickstarts.greeter.web.DeveloperController.inputfilepath.
Referenced by org.jboss.as.quickstarts.greeter.web.DeveloperController.trainmodel().
getModelclassname()
String org.jboss.as.quickstarts.greeter.web.DeveloperController.getModelclassname ()
This function gets the model class name in the database from the developer_page.xhtml.
Returns
the model file path in string format.
Definition at line 138 of file DeveloperController.java.
References org.jboss.as.quickstarts.greeter.web.DeveloperController.modelclassname.
Referenced by org.jboss.as.quickstarts.greeter.web.DeveloperController.calcacc(), and org.jboss.as.quickstarts.greeter.web.DeveloperController.savemodel().
getModelfilepath()
String org.jboss.as.quickstarts.greeter.web.DeveloperController.getModelfilepath ()
This function gets the model file path in HDFS from the developer_page.xhtml.
Returns
the model file path in string format.
Definition at line 106 of file DeveloperController.java.
References org.jboss.as.quickstarts.greeter.web.DeveloperController.modelfilepath.
Referenced by org.jboss.as.quickstarts.greeter.web.DeveloperController.calcacc(), and org.jboss.as.quickstarts.greeter.web.DeveloperController.savemodel().
getOutputfilepath()
String org.jboss.as.quickstarts.greeter.web.DeveloperController.getOutputfilepath ()
This function gets the output file path in HDFS from the developer_page.xhtml.
Returns
the output file path in string format.
Definition at line 122 of file DeveloperController.java.
References org.jboss.as.quickstarts.greeter.web.DeveloperController.outputfilepath.
Referenced by org.jboss.as.quickstarts.greeter.web.DeveloperController.trainmodel().
savemodel()
void org.jboss.as.quickstarts.greeter.web.DeveloperController.savemodel ()
This function calls the saveModel function in the bean to save the clusters in the database.
Definition at line 59 of file DeveloperController.java.
References org.jboss.as.quickstarts.greeter.web.DeveloperController.getModelclassname(), org.jboss.as.quickstarts.greeter.web.DeveloperController.getModelfilepath(), and org.jboss.as.quickstarts.greeter.domain.ModelDao.saveModel().
setInputfilepath()
void org.jboss.as.quickstarts.greeter.web.DeveloperController.setInputfilepath (String inputfilepath)
This function sets the input file path to the developer_page.xhtml.
Parameters
inputfilepath
Definition at line 98 of file DeveloperController.java.
References org.jboss.as.quickstarts.greeter.web.DeveloperController.inputfilepath.
setModelclassname()
void org.jboss.as.quickstarts.greeter.web.DeveloperController.setModelclassname (String modelclassname)
This function sets the model class name to be saved in the database to the developer_page.xhtml.
Parameters
modelclassname
Definition at line 146 of file DeveloperController.java.
References org.jboss.as.quickstarts.greeter.web.DeveloperController.modelclassname.
setModelfilepath()
void org.jboss.as.quickstarts.greeter.web.DeveloperController.setModelfilepath (String modelfilepath)
This function sets the model file path to the developer_page.xhtml.
Parameters
modelfilepath
Definition at line 114 of file DeveloperController.java.
References org.jboss.as.quickstarts.greeter.web.DeveloperController.modelfilepath.
setOutputfilepath()
void org.jboss.as.quickstarts.greeter.web.DeveloperController.setOutputfilepath (String outputfilepath)
This function sets the output file path to the developer_page.xhtml.
Parameters
outputfilepath
Definition at line 130 of file DeveloperController.java.
References org.jboss.as.quickstarts.greeter.web.DeveloperController.outputfilepath.
trainmodel()
void org.jboss.as.quickstarts.greeter.web.DeveloperController.trainmodel ()
This functions calls the trainModel function to create the clusters using Kmeans algorithm.
Definition at line 51 of file DeveloperController.java.
References org.jboss.as.quickstarts.greeter.web.DeveloperController.getInputfilepath(), org.jboss.as.quickstarts.greeter.web.DeveloperController.getOutputfilepath(), and org.jboss.as.quickstarts.greeter.domain.ModelDao.trainModel().
Member Data Documentation
greeting
String org.jboss.as.quickstarts.greeter.web.DeveloperController.greeting private
Definition at line 46 of file DeveloperController.java.
Referenced by org.jboss.as.quickstarts.greeter.web.DeveloperController.getGreeting().
inputfilepath
String org.jboss.as.quickstarts.greeter.web.DeveloperController.inputfilepath private
Definition at line 38 of file DeveloperController.java.
Referenced by org.jboss.as.quickstarts.greeter.web.DeveloperController.getInputfilepath(), and org.jboss.as.quickstarts.greeter.web.DeveloperController.setInputfilepath().
modelclassname
String org.jboss.as.quickstarts.greeter.web.DeveloperController.modelclassname private
Definition at line 40 of file DeveloperController.java.
Referenced by org.jboss.as.quickstarts.greeter.web.DeveloperController.getModelclassname(), and org.jboss.as.quickstarts.greeter.web.DeveloperController.setModelclassname().
modelDao
ModelDao org.jboss.as.quickstarts.greeter.web.DeveloperController.modelDao private
Definition at line 36 of file DeveloperController.java.
modelfilepath
String org.jboss.as.quickstarts.greeter.web.DeveloperController.modelfilepath private
Definition at line 44 of file DeveloperController.java.
Referenced by org.jboss.as.quickstarts.greeter.web.DeveloperController.getModelfilepath(), and org.jboss.as.quickstarts.greeter.web.DeveloperController.setModelfilepath().
outputfilepath
String org.jboss.as.quickstarts.greeter.web.DeveloperController.outputfilepath private
Definition at line 42 of file DeveloperController.java.
Referenced by org.jboss.as.quickstarts.greeter.web.DeveloperController.getOutputfilepath(), and org.jboss.as.quickstarts.greeter.web.DeveloperController.setOutputfilepath().
The documentation for this class was generated from the following file:
src/main/java/org/jboss/as/quickstarts/greeter/web/DeveloperController.java