Vote Prediction: org.jboss.as.quickstarts.greeter.domain.Model Class Reference
org.jboss.as.quickstarts.greeter.domain.Model Class Reference
This class is used to map the "Models" table in the database.
Public Member Functions
Long getId ()
String getName ()
void setName (String name)
String getClassname ()
void setClassname (String classname)
byte [] getObject ()
void setObject (byte[] object)
Timestamp getDate ()
void setDate (Timestamp date)
Private Attributes
Long id
String name
String classname
byte [] object
Timestamp date
Detailed Description
This class is used to map the "Models" table in the database.
Author
MIR
Definition at line 35 of file Model.java.
Member Function Documentation
getClassname()
String org.jboss.as.quickstarts.greeter.domain.Model.getClassname ()
Definition at line 61 of file Model.java.
getDate()
Timestamp org.jboss.as.quickstarts.greeter.domain.Model.getDate ()
Definition at line 77 of file Model.java.
getId()
Long org.jboss.as.quickstarts.greeter.domain.Model.getId ()
Definition at line 49 of file Model.java.
getName()
String org.jboss.as.quickstarts.greeter.domain.Model.getName ()
Definition at line 53 of file Model.java.
getObject()
byte [] org.jboss.as.quickstarts.greeter.domain.Model.getObject ()
Definition at line 69 of file Model.java.
Referenced by org.jboss.as.quickstarts.greeter.domain.ManagedBeanModelDao.predictModel().
setClassname()
void org.jboss.as.quickstarts.greeter.domain.Model.setClassname (String classname)
Definition at line 65 of file Model.java.
Referenced by org.jboss.as.quickstarts.greeter.domain.ManagedBeanModelDao.saveModel().
setDate()
void org.jboss.as.quickstarts.greeter.domain.Model.setDate (Timestamp date)
Definition at line 81 of file Model.java.
Referenced by org.jboss.as.quickstarts.greeter.domain.ManagedBeanModelDao.saveModel().
setName()
void org.jboss.as.quickstarts.greeter.domain.Model.setName (String name)
Definition at line 57 of file Model.java.
Referenced by org.jboss.as.quickstarts.greeter.domain.ManagedBeanModelDao.saveModel().
setObject()
void org.jboss.as.quickstarts.greeter.domain.Model.setObject (byte [] object)
Definition at line 73 of file Model.java.
Referenced by org.jboss.as.quickstarts.greeter.domain.ManagedBeanModelDao.saveModel().
Member Data Documentation
classname
String org.jboss.as.quickstarts.greeter.domain.Model.classname private
Definition at line 43 of file Model.java.
date
Timestamp org.jboss.as.quickstarts.greeter.domain.Model.date private
Definition at line 47 of file Model.java.
id
Long org.jboss.as.quickstarts.greeter.domain.Model.id private
Definition at line 39 of file Model.java.
name
String org.jboss.as.quickstarts.greeter.domain.Model.name private
Definition at line 41 of file Model.java.
object
byte [] org.jboss.as.quickstarts.greeter.domain.Model.object private
Definition at line 45 of file Model.java.
The documentation for this class was generated from the following file:
src/main/java/org/jboss/as/quickstarts/greeter/domain/Model.java