Vote Prediction: org.jboss.as.quickstarts.greeter.web.GreetController Class Reference
org.jboss.as.quickstarts.greeter.web.GreetController Class Reference
This is the controller for main login page.
Public Member Functions
String greet ()
This function calls the getForUsername for user authentication.
String getUsername ()
This function gets the username from the greet.xhtml page.
void setUsername (String username)
This function sets the username to the greet.xhtml page.
int getRole ()
This function gets the role from the greet.xhtml page.
void setRole (int role)
This function sets the role to the greet.xhtml page.
String getPassword ()
This function gets the password from the greet.xhtml page.
void setPassword (String password)
This function sets the password to the greet.xhtml page.
String getGreeting ()
This function gets the message from the greet.xhtml page.
String encode (String value)
This function is used to encode the password fed by the user.
Private Attributes
UserDao userDao
String username
int role
String password
String greeting
Static Private Attributes
static final Logger logger = LoggerFactory.getLogger(GreetController.class.getName())
Detailed Description
This is the controller for main login page.
Author
MIR
Definition at line 42 of file GreetController.java.
Member Function Documentation
encode()
String org.jboss.as.quickstarts.greeter.web.GreetController.encode (String value)
This function is used to encode the password fed by the user.
Returns
encoded password
Definition at line 147 of file GreetController.java.
Referenced by org.jboss.as.quickstarts.greeter.web.GreetController.greet().
getGreeting()
String org.jboss.as.quickstarts.greeter.web.GreetController.getGreeting ()
This function gets the message from the greet.xhtml page.
Returns
message
Definition at line 139 of file GreetController.java.
References org.jboss.as.quickstarts.greeter.web.GreetController.greeting.
getPassword()
String org.jboss.as.quickstarts.greeter.web.GreetController.getPassword ()
This function gets the password from the greet.xhtml page.
Returns
password
Definition at line 123 of file GreetController.java.
References org.jboss.as.quickstarts.greeter.web.GreetController.password.
getRole()
int org.jboss.as.quickstarts.greeter.web.GreetController.getRole ()
This function gets the role from the greet.xhtml page.
Returns
role
Definition at line 107 of file GreetController.java.
References org.jboss.as.quickstarts.greeter.web.GreetController.role.
getUsername()
String org.jboss.as.quickstarts.greeter.web.GreetController.getUsername ()
This function gets the username from the greet.xhtml page.
Returns
username
Definition at line 91 of file GreetController.java.
References org.jboss.as.quickstarts.greeter.web.GreetController.username.
greet()
String org.jboss.as.quickstarts.greeter.web.GreetController.greet ()
This function calls the getForUsername for user authentication.
Returns
returns the page according to the role of the user in the database.
Definition at line 61 of file GreetController.java.
References org.jboss.as.quickstarts.greeter.web.GreetController.encode(), org.jboss.as.quickstarts.greeter.domain.UserDao.getForUsername(), org.jboss.as.quickstarts.greeter.domain.User.getPassword(), org.jboss.as.quickstarts.greeter.domain.User.getRole(), and org.jboss.as.quickstarts.greeter.domain.User.getUsername().
setPassword()
void org.jboss.as.quickstarts.greeter.web.GreetController.setPassword (String password)
This function sets the password to the greet.xhtml page.
Parameters
password
Definition at line 131 of file GreetController.java.
References org.jboss.as.quickstarts.greeter.web.GreetController.password.
setRole()
void org.jboss.as.quickstarts.greeter.web.GreetController.setRole (int role)
This function sets the role to the greet.xhtml page.
Parameters
role
Definition at line 115 of file GreetController.java.
References org.jboss.as.quickstarts.greeter.web.GreetController.role.
setUsername()
void org.jboss.as.quickstarts.greeter.web.GreetController.setUsername (String username)
This function sets the username to the greet.xhtml page.
Parameters
username
Definition at line 99 of file GreetController.java.
References org.jboss.as.quickstarts.greeter.web.GreetController.username.
Member Data Documentation
greeting
String org.jboss.as.quickstarts.greeter.web.GreetController.greeting private
Definition at line 53 of file GreetController.java.
Referenced by org.jboss.as.quickstarts.greeter.web.GreetController.getGreeting().
logger
final Logger org.jboss.as.quickstarts.greeter.web.GreetController.logger = LoggerFactory.getLogger(GreetController.class.getName()) static private
Definition at line 55 of file GreetController.java.
password
String org.jboss.as.quickstarts.greeter.web.GreetController.password private
Definition at line 51 of file GreetController.java.
Referenced by org.jboss.as.quickstarts.greeter.web.GreetController.getPassword(), and org.jboss.as.quickstarts.greeter.web.GreetController.setPassword().
role
int org.jboss.as.quickstarts.greeter.web.GreetController.role private
Definition at line 49 of file GreetController.java.
Referenced by org.jboss.as.quickstarts.greeter.web.GreetController.getRole(), and org.jboss.as.quickstarts.greeter.web.GreetController.setRole().
userDao
UserDao org.jboss.as.quickstarts.greeter.web.GreetController.userDao private
Definition at line 45 of file GreetController.java.
username
String org.jboss.as.quickstarts.greeter.web.GreetController.username private
Definition at line 47 of file GreetController.java.
Referenced by org.jboss.as.quickstarts.greeter.web.GreetController.getUsername(), and org.jboss.as.quickstarts.greeter.web.GreetController.setUsername().
The documentation for this class was generated from the following file:
src/main/java/org/jboss/as/quickstarts/greeter/web/GreetController.java