Vote Prediction: org.jboss.as.quickstarts.greeter.web.GeneralController Class Reference
org.jboss.as.quickstarts.greeter.web.GeneralController Class Reference
This is the controller for prediction from the clusters.
Public Member Functions
void predictmodel ()
This functions calls the predictModel function to predict which party does the particular voter support.
String getInput1 ()
This function gets the rating for HANDICAPPED-INFANTS from the developer_page.xhtml.
void setInput1 (String input1)
This function sets the rating for HANDICAPPED-INFANTS to the developer_page.xhtml.
String getInput2 ()
This function gets the rating for WATER-PROJECT-COST-SHARING from the developer_page.xhtml.
void setInput2 (String input2)
This function sets the rating for WATER-PROJECT-COST-SHARING to the developer_page.xhtml.
String getInput3 ()
This function gets the rating for ADOPTION-OF-THE-BUDGET-RESOLUTION from the developer_page.xhtml.
void setInput3 (String input3)
This function sets the rating for ADOPTION-OF-THE-BUDGET-RESOLUTION to the developer_page.xhtml.
String getInput4 ()
This function gets the rating for PHYSICIAN-FEE-FREEZE from the developer_page.xhtml.
void setInput4 (String input4)
This function sets the rating for PHYSICIAN-FEE-FREEZE to the developer_page.xhtml.
String getInput5 ()
This function gets the rating for EL-SALVADOR-AID from the developer_page.xhtml.
void setInput5 (String input5)
This function sets the rating for EL-SALVADOR-AID to the developer_page.xhtml.
String getInput6 ()
This function gets the rating for RELIGIOUS-GROUPS-IN-SCHOOLS from the developer_page.xhtml.
void setInput6 (String input6)
This function sets the rating for RELIGIOUS-GROUPS-IN-SCHOOLS to the developer_page.xhtml.
String getInput7 ()
This function gets the rating for ANTI-SATELLITE-TEST-BAN from the developer_page.xhtml.
void setInput7 (String input7)
This function sets the rating for ANTI-SATELLITE-TEST-BAN to the developer_page.xhtml.
String getInput8 ()
This function gets the rating for AID-TO-NICARAGUAN-CONTRAS from the developer_page.xhtml.
void setInput8 (String input8)
This function sets the rating for AID-TO-NICARAGUAN-CONTRAS to the developer_page.xhtml.
String getInput9 ()
This function gets the rating for MX-MISSILE from the developer_page.xhtml.
void setInput9 (String input9)
This function sets the rating for MX-MISSILE to the developer_page.xhtml.
String getInput10 ()
This function gets the rating for IMMIGRATION from the developer_page.xhtml.
void setInput10 (String input10)
This function sets the rating for IMMIGRATION to the developer_page.xhtml.
String getInput11 ()
This function gets the rating for SYNFUELS-CORPORATION-CUTBACK from the developer_page.xhtml.
void setInput11 (String input11)
This function sets the rating for SYNFUELS-CORPORATION-CUTBACK to the developer_page.xhtml.
String getInput12 ()
This function gets the rating for EDUCATION-SPENDING from the developer_page.xhtml.
void setInput12 (String input12)
This function sets the rating for EDUCATION-SPENDING to the developer_page.xhtml.
String getInput13 ()
This function gets the rating for SUPERFUND-RIGHT-TO-SUE from the developer_page.xhtml.
void setInput13 (String input13)
This function sets the rating for SUPERFUND-RIGHT-TO-SUE to the developer_page.xhtml.
String getInput14 ()
This function gets the rating for CRIME from the developer_page.xhtml.
void setInput14 (String input14)
This function sets the rating for CRIME to the developer_page.xhtml.
String getInput15 ()
This function gets the rating for DUTY-FREE-EXPORTS from the developer_page.xhtml.
void setInput15 (String input15)
This function sets the rating for DUTY-FREE-EXPORTS to the developer_page.xhtml.
String getInput16 ()
This function gets the rating for EXPORT-ADMINISTRATION-ACT-SOUTH-AFRICA from the developer_page.xhtml.
void setInput16 (String input16)
This function sets the rating for EXPORT-ADMINISTRATION-ACT-SOUTH-AFRICA to the developer_page.xhtml.
String getModel ()
This function gets the class name in the database from the developer_page.xhtml.
void setModel (String model)
This function sets the class name in the database to the developer_page.xhtml.
String getGreeting ()
This function gets the greeting attribute from the general_page.XHTML page.
Private Attributes
ModelDao modelDao
String input1
String input2
String input3
String input4
String input5
String input6
String input7
String input8
String input9
String input10
String input11
String input12
String input13
String input14
String input15
String input16
String model
String greeting
Detailed Description
This is the controller for prediction from the clusters.
Author
MIR
Definition at line 34 of file GeneralController.java.
Member Function Documentation
getGreeting()
String org.jboss.as.quickstarts.greeter.web.GeneralController.getGreeting ()
This function gets the greeting attribute from the general_page.XHTML page.
Definition at line 344 of file GeneralController.java.
References org.jboss.as.quickstarts.greeter.web.GeneralController.greeting.
getInput1()
String org.jboss.as.quickstarts.greeter.web.GeneralController.getInput1 ()
This function gets the rating for HANDICAPPED-INFANTS from the developer_page.xhtml.
Returns
the grade out of 100 in string format.
Definition at line 73 of file GeneralController.java.
References org.jboss.as.quickstarts.greeter.web.GeneralController.input1.
Referenced by org.jboss.as.quickstarts.greeter.web.GeneralController.predictmodel().
getInput10()
String org.jboss.as.quickstarts.greeter.web.GeneralController.getInput10 ()
This function gets the rating for IMMIGRATION from the developer_page.xhtml.
Returns
the grade out of 100 in string format.
Definition at line 217 of file GeneralController.java.
References org.jboss.as.quickstarts.greeter.web.GeneralController.input10.
Referenced by org.jboss.as.quickstarts.greeter.web.GeneralController.predictmodel().
getInput11()
String org.jboss.as.quickstarts.greeter.web.GeneralController.getInput11 ()
This function gets the rating for SYNFUELS-CORPORATION-CUTBACK from the developer_page.xhtml.
Returns
the grade out of 100 in string format.
Definition at line 233 of file GeneralController.java.
References org.jboss.as.quickstarts.greeter.web.GeneralController.input11.
Referenced by org.jboss.as.quickstarts.greeter.web.GeneralController.predictmodel().
getInput12()
String org.jboss.as.quickstarts.greeter.web.GeneralController.getInput12 ()
This function gets the rating for EDUCATION-SPENDING from the developer_page.xhtml.
Returns
the grade out of 100 in string format.
Definition at line 249 of file GeneralController.java.
References org.jboss.as.quickstarts.greeter.web.GeneralController.input12.
Referenced by org.jboss.as.quickstarts.greeter.web.GeneralController.predictmodel().
getInput13()
String org.jboss.as.quickstarts.greeter.web.GeneralController.getInput13 ()
This function gets the rating for SUPERFUND-RIGHT-TO-SUE from the developer_page.xhtml.
Returns
the grade out of 100 in string format.
Definition at line 265 of file GeneralController.java.
References org.jboss.as.quickstarts.greeter.web.GeneralController.input13.
Referenced by org.jboss.as.quickstarts.greeter.web.GeneralController.predictmodel().
getInput14()
String org.jboss.as.quickstarts.greeter.web.GeneralController.getInput14 ()
This function gets the rating for CRIME from the developer_page.xhtml.
Returns
the grade out of 100 in string format.
Definition at line 281 of file GeneralController.java.
References org.jboss.as.quickstarts.greeter.web.GeneralController.input14.
Referenced by org.jboss.as.quickstarts.greeter.web.GeneralController.predictmodel().
getInput15()
String org.jboss.as.quickstarts.greeter.web.GeneralController.getInput15 ()
This function gets the rating for DUTY-FREE-EXPORTS from the developer_page.xhtml.
Returns
the grade out of 100 in string format.
Definition at line 297 of file GeneralController.java.
References org.jboss.as.quickstarts.greeter.web.GeneralController.input15.
Referenced by org.jboss.as.quickstarts.greeter.web.GeneralController.predictmodel().
getInput16()
String org.jboss.as.quickstarts.greeter.web.GeneralController.getInput16 ()
This function gets the rating for EXPORT-ADMINISTRATION-ACT-SOUTH-AFRICA from the developer_page.xhtml.
Returns
the grade out of 100 in string format.
Definition at line 313 of file GeneralController.java.
References org.jboss.as.quickstarts.greeter.web.GeneralController.input16.
Referenced by org.jboss.as.quickstarts.greeter.web.GeneralController.predictmodel().
getInput2()
String org.jboss.as.quickstarts.greeter.web.GeneralController.getInput2 ()
This function gets the rating for WATER-PROJECT-COST-SHARING from the developer_page.xhtml.
Returns
the grade out of 100 in string format.
Definition at line 89 of file GeneralController.java.
References org.jboss.as.quickstarts.greeter.web.GeneralController.input2.
Referenced by org.jboss.as.quickstarts.greeter.web.GeneralController.predictmodel().
getInput3()
String org.jboss.as.quickstarts.greeter.web.GeneralController.getInput3 ()
This function gets the rating for ADOPTION-OF-THE-BUDGET-RESOLUTION from the developer_page.xhtml.
Returns
the grade out of 100 in string format.
Definition at line 105 of file GeneralController.java.
References org.jboss.as.quickstarts.greeter.web.GeneralController.input3.
Referenced by org.jboss.as.quickstarts.greeter.web.GeneralController.predictmodel().
getInput4()
String org.jboss.as.quickstarts.greeter.web.GeneralController.getInput4 ()
This function gets the rating for PHYSICIAN-FEE-FREEZE from the developer_page.xhtml.
Returns
the grade out of 100 in string format.
Definition at line 121 of file GeneralController.java.
References org.jboss.as.quickstarts.greeter.web.GeneralController.input4.
Referenced by org.jboss.as.quickstarts.greeter.web.GeneralController.predictmodel().
getInput5()
String org.jboss.as.quickstarts.greeter.web.GeneralController.getInput5 ()
This function gets the rating for EL-SALVADOR-AID from the developer_page.xhtml.
Returns
the grade out of 100 in string format.
Definition at line 137 of file GeneralController.java.
References org.jboss.as.quickstarts.greeter.web.GeneralController.input5.
Referenced by org.jboss.as.quickstarts.greeter.web.GeneralController.predictmodel().
getInput6()
String org.jboss.as.quickstarts.greeter.web.GeneralController.getInput6 ()
This function gets the rating for RELIGIOUS-GROUPS-IN-SCHOOLS from the developer_page.xhtml.
Returns
the grade out of 100 in string format.
Definition at line 153 of file GeneralController.java.
References org.jboss.as.quickstarts.greeter.web.GeneralController.input6.
Referenced by org.jboss.as.quickstarts.greeter.web.GeneralController.predictmodel().
getInput7()
String org.jboss.as.quickstarts.greeter.web.GeneralController.getInput7 ()
This function gets the rating for ANTI-SATELLITE-TEST-BAN from the developer_page.xhtml.
Returns
the grade out of 100 in string format.
Definition at line 169 of file GeneralController.java.
References org.jboss.as.quickstarts.greeter.web.GeneralController.input7.
Referenced by org.jboss.as.quickstarts.greeter.web.GeneralController.predictmodel().
getInput8()
String org.jboss.as.quickstarts.greeter.web.GeneralController.getInput8 ()
This function gets the rating for AID-TO-NICARAGUAN-CONTRAS from the developer_page.xhtml.
Returns
the grade out of 100 in string format.
Definition at line 185 of file GeneralController.java.
References org.jboss.as.quickstarts.greeter.web.GeneralController.input8.
Referenced by org.jboss.as.quickstarts.greeter.web.GeneralController.predictmodel().
getInput9()
String org.jboss.as.quickstarts.greeter.web.GeneralController.getInput9 ()
This function gets the rating for MX-MISSILE from the developer_page.xhtml.
Returns
the grade out of 100 in string format.
Definition at line 201 of file GeneralController.java.
References org.jboss.as.quickstarts.greeter.web.GeneralController.input9.
Referenced by org.jboss.as.quickstarts.greeter.web.GeneralController.predictmodel().
getModel()
String org.jboss.as.quickstarts.greeter.web.GeneralController.getModel ()
This function gets the class name in the database from the developer_page.xhtml.
Returns
the grade out of 100 in string format.
Definition at line 329 of file GeneralController.java.
References org.jboss.as.quickstarts.greeter.web.GeneralController.model.
Referenced by org.jboss.as.quickstarts.greeter.web.GeneralController.predictmodel().
predictmodel()
void org.jboss.as.quickstarts.greeter.web.GeneralController.predictmodel ()
This functions calls the predictModel function to predict which party does the particular voter support.
Definition at line 64 of file GeneralController.java.
References org.jboss.as.quickstarts.greeter.web.GeneralController.getInput1(), org.jboss.as.quickstarts.greeter.web.GeneralController.getInput10(), org.jboss.as.quickstarts.greeter.web.GeneralController.getInput11(), org.jboss.as.quickstarts.greeter.web.GeneralController.getInput12(), org.jboss.as.quickstarts.greeter.web.GeneralController.getInput13(), org.jboss.as.quickstarts.greeter.web.GeneralController.getInput14(), org.jboss.as.quickstarts.greeter.web.GeneralController.getInput15(), org.jboss.as.quickstarts.greeter.web.GeneralController.getInput16(), org.jboss.as.quickstarts.greeter.web.GeneralController.getInput2(), org.jboss.as.quickstarts.greeter.web.GeneralController.getInput3(), org.jboss.as.quickstarts.greeter.web.GeneralController.getInput4(), org.jboss.as.quickstarts.greeter.web.GeneralController.getInput5(), org.jboss.as.quickstarts.greeter.web.GeneralController.getInput6(), org.jboss.as.quickstarts.greeter.web.GeneralController.getInput7(), org.jboss.as.quickstarts.greeter.web.GeneralController.getInput8(), org.jboss.as.quickstarts.greeter.web.GeneralController.getInput9(), org.jboss.as.quickstarts.greeter.web.GeneralController.getModel(), and org.jboss.as.quickstarts.greeter.domain.ModelDao.predictModel().
setInput1()
void org.jboss.as.quickstarts.greeter.web.GeneralController.setInput1 (String input1)
This function sets the rating for HANDICAPPED-INFANTS to the developer_page.xhtml.
Parameters
input1 rating out of 100in string
Definition at line 81 of file GeneralController.java.
References org.jboss.as.quickstarts.greeter.web.GeneralController.input1.
setInput10()
void org.jboss.as.quickstarts.greeter.web.GeneralController.setInput10 (String input10)
This function sets the rating for IMMIGRATION to the developer_page.xhtml.
Parameters
input1 rating out of 100in string
Definition at line 225 of file GeneralController.java.
References org.jboss.as.quickstarts.greeter.web.GeneralController.input10.
setInput11()
void org.jboss.as.quickstarts.greeter.web.GeneralController.setInput11 (String input11)
This function sets the rating for SYNFUELS-CORPORATION-CUTBACK to the developer_page.xhtml.
Parameters
input1 rating out of 100in string
Definition at line 241 of file GeneralController.java.
References org.jboss.as.quickstarts.greeter.web.GeneralController.input11.
setInput12()
void org.jboss.as.quickstarts.greeter.web.GeneralController.setInput12 (String input12)
This function sets the rating for EDUCATION-SPENDING to the developer_page.xhtml.
Parameters
input1 rating out of 100in string
Definition at line 257 of file GeneralController.java.
References org.jboss.as.quickstarts.greeter.web.GeneralController.input12.
setInput13()
void org.jboss.as.quickstarts.greeter.web.GeneralController.setInput13 (String input13)
This function sets the rating for SUPERFUND-RIGHT-TO-SUE to the developer_page.xhtml.
Parameters
input1 rating out of 100in string
Definition at line 273 of file GeneralController.java.
References org.jboss.as.quickstarts.greeter.web.GeneralController.input13.
setInput14()
void org.jboss.as.quickstarts.greeter.web.GeneralController.setInput14 (String input14)
This function sets the rating for CRIME to the developer_page.xhtml.
Parameters
input1 rating out of 100in string
Definition at line 289 of file GeneralController.java.
References org.jboss.as.quickstarts.greeter.web.GeneralController.input14.
setInput15()
void org.jboss.as.quickstarts.greeter.web.GeneralController.setInput15 (String input15)
This function sets the rating for DUTY-FREE-EXPORTS to the developer_page.xhtml.
Parameters
input1 rating out of 100in string
Definition at line 305 of file GeneralController.java.
References org.jboss.as.quickstarts.greeter.web.GeneralController.input15.
setInput16()
void org.jboss.as.quickstarts.greeter.web.GeneralController.setInput16 (String input16)
This function sets the rating for EXPORT-ADMINISTRATION-ACT-SOUTH-AFRICA to the developer_page.xhtml.
Parameters
input1 rating out of 100in string
Definition at line 321 of file GeneralController.java.
References org.jboss.as.quickstarts.greeter.web.GeneralController.input16.
setInput2()
void org.jboss.as.quickstarts.greeter.web.GeneralController.setInput2 (String input2)
This function sets the rating for WATER-PROJECT-COST-SHARING to the developer_page.xhtml.
Parameters
input1 rating out of 100in string
Definition at line 97 of file GeneralController.java.
References org.jboss.as.quickstarts.greeter.web.GeneralController.input2.
setInput3()
void org.jboss.as.quickstarts.greeter.web.GeneralController.setInput3 (String input3)
This function sets the rating for ADOPTION-OF-THE-BUDGET-RESOLUTION to the developer_page.xhtml.
Parameters
input1 rating out of 100in string
Definition at line 113 of file GeneralController.java.
References org.jboss.as.quickstarts.greeter.web.GeneralController.input3.
setInput4()
void org.jboss.as.quickstarts.greeter.web.GeneralController.setInput4 (String input4)
This function sets the rating for PHYSICIAN-FEE-FREEZE to the developer_page.xhtml.
Parameters
input1 rating out of 100in string
Definition at line 129 of file GeneralController.java.
References org.jboss.as.quickstarts.greeter.web.GeneralController.input4.
setInput5()
void org.jboss.as.quickstarts.greeter.web.GeneralController.setInput5 (String input5)
This function sets the rating for EL-SALVADOR-AID to the developer_page.xhtml.
Parameters
input1 rating out of 100in string
Definition at line 145 of file GeneralController.java.
References org.jboss.as.quickstarts.greeter.web.GeneralController.input5.
setInput6()
void org.jboss.as.quickstarts.greeter.web.GeneralController.setInput6 (String input6)
This function sets the rating for RELIGIOUS-GROUPS-IN-SCHOOLS to the developer_page.xhtml.
Parameters
input1 rating out of 100in string
Definition at line 161 of file GeneralController.java.
References org.jboss.as.quickstarts.greeter.web.GeneralController.input6.
setInput7()
void org.jboss.as.quickstarts.greeter.web.GeneralController.setInput7 (String input7)
This function sets the rating for ANTI-SATELLITE-TEST-BAN to the developer_page.xhtml.
Parameters
input1 rating out of 100in string
Definition at line 177 of file GeneralController.java.
References org.jboss.as.quickstarts.greeter.web.GeneralController.input7.
setInput8()
void org.jboss.as.quickstarts.greeter.web.GeneralController.setInput8 (String input8)
This function sets the rating for AID-TO-NICARAGUAN-CONTRAS to the developer_page.xhtml.
Parameters
input1 rating out of 100in string
Definition at line 193 of file GeneralController.java.
References org.jboss.as.quickstarts.greeter.web.GeneralController.input8.
setInput9()
void org.jboss.as.quickstarts.greeter.web.GeneralController.setInput9 (String input9)
This function sets the rating for MX-MISSILE to the developer_page.xhtml.
Parameters
input1 rating out of 100in string
Definition at line 209 of file GeneralController.java.
References org.jboss.as.quickstarts.greeter.web.GeneralController.input9.
setModel()
void org.jboss.as.quickstarts.greeter.web.GeneralController.setModel (String model)
This function sets the class name in the database to the developer_page.xhtml.
Parameters
input1 rating out of 100in string
Definition at line 337 of file GeneralController.java.
References org.jboss.as.quickstarts.greeter.web.GeneralController.model.
Member Data Documentation
greeting
String org.jboss.as.quickstarts.greeter.web.GeneralController.greeting private
Definition at line 59 of file GeneralController.java.
Referenced by org.jboss.as.quickstarts.greeter.web.GeneralController.getGreeting().
input1
String org.jboss.as.quickstarts.greeter.web.GeneralController.input1 private
Definition at line 39 of file GeneralController.java.
Referenced by org.jboss.as.quickstarts.greeter.web.GeneralController.getInput1(), and org.jboss.as.quickstarts.greeter.web.GeneralController.setInput1().
input10
String org.jboss.as.quickstarts.greeter.web.GeneralController.input10 private
Definition at line 49 of file GeneralController.java.
Referenced by org.jboss.as.quickstarts.greeter.web.GeneralController.getInput10(), and org.jboss.as.quickstarts.greeter.web.GeneralController.setInput10().
input11
String org.jboss.as.quickstarts.greeter.web.GeneralController.input11 private
Definition at line 50 of file GeneralController.java.
Referenced by org.jboss.as.quickstarts.greeter.web.GeneralController.getInput11(), and org.jboss.as.quickstarts.greeter.web.GeneralController.setInput11().
input12
String org.jboss.as.quickstarts.greeter.web.GeneralController.input12 private
Definition at line 51 of file GeneralController.java.
Referenced by org.jboss.as.quickstarts.greeter.web.GeneralController.getInput12(), and org.jboss.as.quickstarts.greeter.web.GeneralController.setInput12().
input13
String org.jboss.as.quickstarts.greeter.web.GeneralController.input13 private
Definition at line 52 of file GeneralController.java.
Referenced by org.jboss.as.quickstarts.greeter.web.GeneralController.getInput13(), and org.jboss.as.quickstarts.greeter.web.GeneralController.setInput13().
input14
String org.jboss.as.quickstarts.greeter.web.GeneralController.input14 private
Definition at line 53 of file GeneralController.java.
Referenced by org.jboss.as.quickstarts.greeter.web.GeneralController.getInput14(), and org.jboss.as.quickstarts.greeter.web.GeneralController.setInput14().
input15
String org.jboss.as.quickstarts.greeter.web.GeneralController.input15 private
Definition at line 54 of file GeneralController.java.
Referenced by org.jboss.as.quickstarts.greeter.web.GeneralController.getInput15(), and org.jboss.as.quickstarts.greeter.web.GeneralController.setInput15().
input16
String org.jboss.as.quickstarts.greeter.web.GeneralController.input16 private
Definition at line 55 of file GeneralController.java.
Referenced by org.jboss.as.quickstarts.greeter.web.GeneralController.getInput16(), and org.jboss.as.quickstarts.greeter.web.GeneralController.setInput16().
input2
String org.jboss.as.quickstarts.greeter.web.GeneralController.input2 private
Definition at line 41 of file GeneralController.java.
Referenced by org.jboss.as.quickstarts.greeter.web.GeneralController.getInput2(), and org.jboss.as.quickstarts.greeter.web.GeneralController.setInput2().
input3
String org.jboss.as.quickstarts.greeter.web.GeneralController.input3 private
Definition at line 42 of file GeneralController.java.
Referenced by org.jboss.as.quickstarts.greeter.web.GeneralController.getInput3(), and org.jboss.as.quickstarts.greeter.web.GeneralController.setInput3().
input4
String org.jboss.as.quickstarts.greeter.web.GeneralController.input4 private
Definition at line 43 of file GeneralController.java.
Referenced by org.jboss.as.quickstarts.greeter.web.GeneralController.getInput4(), and org.jboss.as.quickstarts.greeter.web.GeneralController.setInput4().
input5
String org.jboss.as.quickstarts.greeter.web.GeneralController.input5 private
Definition at line 44 of file GeneralController.java.
Referenced by org.jboss.as.quickstarts.greeter.web.GeneralController.getInput5(), and org.jboss.as.quickstarts.greeter.web.GeneralController.setInput5().
input6
String org.jboss.as.quickstarts.greeter.web.GeneralController.input6 private
Definition at line 45 of file GeneralController.java.
Referenced by org.jboss.as.quickstarts.greeter.web.GeneralController.getInput6(), and org.jboss.as.quickstarts.greeter.web.GeneralController.setInput6().
input7
String org.jboss.as.quickstarts.greeter.web.GeneralController.input7 private
Definition at line 46 of file GeneralController.java.
Referenced by org.jboss.as.quickstarts.greeter.web.GeneralController.getInput7(), and org.jboss.as.quickstarts.greeter.web.GeneralController.setInput7().
input8
String org.jboss.as.quickstarts.greeter.web.GeneralController.input8 private
Definition at line 47 of file GeneralController.java.
Referenced by org.jboss.as.quickstarts.greeter.web.GeneralController.getInput8(), and org.jboss.as.quickstarts.greeter.web.GeneralController.setInput8().
input9
String org.jboss.as.quickstarts.greeter.web.GeneralController.input9 private
Definition at line 48 of file GeneralController.java.
Referenced by org.jboss.as.quickstarts.greeter.web.GeneralController.getInput9(), and org.jboss.as.quickstarts.greeter.web.GeneralController.setInput9().
model
String org.jboss.as.quickstarts.greeter.web.GeneralController.model private
Definition at line 57 of file GeneralController.java.
Referenced by org.jboss.as.quickstarts.greeter.web.GeneralController.getModel(), and org.jboss.as.quickstarts.greeter.web.GeneralController.setModel().
modelDao
ModelDao org.jboss.as.quickstarts.greeter.web.GeneralController.modelDao private
Definition at line 37 of file GeneralController.java.
The documentation for this class was generated from the following file:
src/main/java/org/jboss/as/quickstarts/greeter/web/GeneralController.java