Vote Prediction: org.jboss.as.quickstarts.greeter.domain.ManagedBeanModelDao Class Reference
org.jboss.as.quickstarts.greeter.domain.ManagedBeanModelDao Class Reference
This class is implements the ModelDao interface. This class is used for all the data related operations.
Public Member Functions
String trainModel (String Inputfilepath, String Outputfilepath)
This function executes the ECJMSProducer.jar file which in turn invokes a Message driven bean which again calls an EJB to create clusters using Kmeans algorithm.
String saveModel (String modelFilepath, String modelClassname) throws FileNotFoundException, IOException
This function saves the cluster in the database.
String predictModel (String input1, String input2, String input3, String input4, String input5, String input6, String input7, String input8, String input9, String input10, String input11, String input12, String input13, String input14, String input15, String input16, String Modelname)
This function has the logic to the predict which party a particular voter would support using the clusters in the database.
String calcAccuracy (String inputpath, String ModelClassName) throws IOException
This function is used to calculate the accuracy of the algorithm.
Static Public Member Functions
static Object read (ResultSet rs, String columnname) throws SQLException, IOException, ClassNotFoundException
This is used the convert the result set into bytearray stream.
Private Attributes
EntityManager entityManager
UserTransaction utx
Static Private Attributes
static final Logger logger = LoggerFactory.getLogger(ManagedBeanModelDao.class.getName())
Detailed Description
This class is implements the ModelDao interface. This class is used for all the data related operations.
Author
MIR
Definition at line 55 of file ManagedBeanModelDao.java.
Member Function Documentation
calcAccuracy()
String org.jboss.as.quickstarts.greeter.domain.ManagedBeanModelDao.calcAccuracy (String inputpath, String ModelClassName) throws IOException
This function is used to calculate the accuracy of the algorithm.
Implements org.jboss.as.quickstarts.greeter.domain.ModelDao.
Definition at line 559 of file ManagedBeanModelDao.java.
References org.jboss.as.quickstarts.greeter.domain.MainCluster.getData(), org.jboss.as.quickstarts.greeter.domain.ManagedBeanModelDao.predictModel(), org.jboss.as.quickstarts.greeter.domain.ClusterModel.setData(), and org.jboss.as.quickstarts.greeter.domain.MainCluster.setData().
predictModel()
String org.jboss.as.quickstarts.greeter.domain.ManagedBeanModelDao.predictModel (String input1, String input2, String input3, String input4, String input5, String input6, String input7, String input8, String input9, String input10, String input11, String input12, String input13, String input14, String input15, String input16, String Modelname)
This function has the logic to the predict which party a particular voter would support using the clusters in the database.
Implements org.jboss.as.quickstarts.greeter.domain.ModelDao.
Definition at line 207 of file ManagedBeanModelDao.java.
References org.jboss.as.quickstarts.greeter.domain.MainCluster.getData(), and org.jboss.as.quickstarts.greeter.domain.Model.getObject().
Referenced by org.jboss.as.quickstarts.greeter.domain.ManagedBeanModelDao.calcAccuracy().
read()
static Object org.jboss.as.quickstarts.greeter.domain.ManagedBeanModelDao.read (ResultSet rs, String columnname) throws SQLException, IOException, ClassNotFoundException static
This is used the convert the result set into bytearray stream.
Parameters
rs
columnname
Returns
Exceptions
SQLException
IOException
ClassNotFoundException
Definition at line 546 of file ManagedBeanModelDao.java.
saveModel()
String org.jboss.as.quickstarts.greeter.domain.ManagedBeanModelDao.saveModel (String modelFilepath, String modelClassname) throws FileNotFoundException, IOException
This function saves the cluster in the database.
Implements org.jboss.as.quickstarts.greeter.domain.ModelDao.
Definition at line 103 of file ManagedBeanModelDao.java.
References org.jboss.as.quickstarts.greeter.domain.Model.setClassname(), org.jboss.as.quickstarts.greeter.domain.ClusterModel.setData(), org.jboss.as.quickstarts.greeter.domain.MainCluster.setData(), org.jboss.as.quickstarts.greeter.domain.Model.setDate(), org.jboss.as.quickstarts.greeter.domain.Model.setName(), and org.jboss.as.quickstarts.greeter.domain.Model.setObject().
trainModel()
String org.jboss.as.quickstarts.greeter.domain.ManagedBeanModelDao.trainModel (String Inputfilepath, String Outputfilepath)
This function executes the ECJMSProducer.jar file which in turn invokes a Message driven bean which again calls an EJB to create clusters using Kmeans algorithm.
Implements org.jboss.as.quickstarts.greeter.domain.ModelDao.
Definition at line 68 of file ManagedBeanModelDao.java.
Member Data Documentation
entityManager
EntityManager org.jboss.as.quickstarts.greeter.domain.ManagedBeanModelDao.entityManager private
Definition at line 58 of file ManagedBeanModelDao.java.
logger
final Logger org.jboss.as.quickstarts.greeter.domain.ManagedBeanModelDao.logger = LoggerFactory.getLogger(ManagedBeanModelDao.class.getName()) static private
Definition at line 63 of file ManagedBeanModelDao.java.
utx
UserTransaction org.jboss.as.quickstarts.greeter.domain.ManagedBeanModelDao.utx private
Definition at line 61 of file ManagedBeanModelDao.java.
The documentation for this class was generated from the following file:
src/main/java/org/jboss/as/quickstarts/greeter/domain/ManagedBeanModelDao.java