Vote Prediction: org.jboss.as.quickstarts.greeter.domain.UserDao Interface Reference
org.jboss.as.quickstarts.greeter.domain.UserDao Interface Reference
This interface consists of all the user related operations.
Public Member Functions
User getForUsername (String username)
void changeUserRole (User user)
Detailed Description
This interface consists of all the user related operations.
Author
MIR
Definition at line 24 of file UserDao.java.
Member Function Documentation
changeUserRole()
void org.jboss.as.quickstarts.greeter.domain.UserDao.changeUserRole (User user)
Implemented in org.jboss.as.quickstarts.greeter.domain.ManagedBeanUserDao, and org.jboss.as.quickstarts.greeter.domain.EJBUserDao.
Referenced by org.jboss.as.quickstarts.greeter.web.AdminController.change().
getForUsername()
User org.jboss.as.quickstarts.greeter.domain.UserDao.getForUsername (String username)
Implemented in org.jboss.as.quickstarts.greeter.domain.ManagedBeanUserDao, and org.jboss.as.quickstarts.greeter.domain.EJBUserDao.
Referenced by org.jboss.as.quickstarts.greeter.web.AdminController.change(), and org.jboss.as.quickstarts.greeter.web.GreetController.greet().
The documentation for this interface was generated from the following file:
src/main/java/org/jboss/as/quickstarts/greeter/domain/UserDao.java