Vote Prediction: org.jboss.as.quickstarts.greeter.domain.ModelDao Interface Reference
org.jboss.as.quickstarts.greeter.domain.ModelDao Interface Reference
This interface consists of all the model related operations.
Public Member Functions
String trainModel (String input, String Output)
This function trains the data using Kmeans algorithm and creates clusters.
String saveModel (String modelfilepath, String modelClassName) throws FileNotFoundException, IOException
This function saves the cluster in the database.
String predictModel (String input1, String input2, String input3, String input4, String input5, String input6, String input7, String input8, String input9, String input10, String input11, String input12, String input13, String input14, String input15, String input16, String Model)
This function predicts which party would the voter support.
String calcAccuracy (String inputpath, String ModelClassName) throws IOException
This function calculates the accuracy of the algorithm used.
Detailed Description
This interface consists of all the model related operations.
Author
MIR
Definition at line 27 of file ModelDao.java.
Member Function Documentation
calcAccuracy()
String org.jboss.as.quickstarts.greeter.domain.ModelDao.calcAccuracy (String inputpath, String ModelClassName) throws IOException
This function calculates the accuracy of the algorithm used.
Parameters
inputpath
ModelClassName
Returns
Exceptions
IOException
Implemented in org.jboss.as.quickstarts.greeter.domain.ManagedBeanModelDao.
Referenced by org.jboss.as.quickstarts.greeter.web.DeveloperController.calcacc().
predictModel()
String org.jboss.as.quickstarts.greeter.domain.ModelDao.predictModel (String input1, String input2, String input3, String input4, String input5, String input6, String input7, String input8, String input9, String input10, String input11, String input12, String input13, String input14, String input15, String input16, String Model)
This function predicts which party would the voter support.
Parameters
input1
input2
input3
input4
input5
input6
input7
input8
input9
input10
input11
input12
input13
input14
input15
input16
Model
Returns
Implemented in org.jboss.as.quickstarts.greeter.domain.ManagedBeanModelDao.
Referenced by org.jboss.as.quickstarts.greeter.web.GeneralController.predictmodel().
saveModel()
String org.jboss.as.quickstarts.greeter.domain.ModelDao.saveModel (String modelfilepath, String modelClassName) throws FileNotFoundException, IOException
This function saves the cluster in the database.
Parameters
modelfilepath
modelClassName
Returns
Exceptions
FileNotFoundException
IOException
Implemented in org.jboss.as.quickstarts.greeter.domain.ManagedBeanModelDao.
Referenced by org.jboss.as.quickstarts.greeter.web.DeveloperController.savemodel().
trainModel()
String org.jboss.as.quickstarts.greeter.domain.ModelDao.trainModel (String input, String Output)
This function trains the data using Kmeans algorithm and creates clusters.
Parameters
input
Output
Returns
Implemented in org.jboss.as.quickstarts.greeter.domain.ManagedBeanModelDao.
Referenced by org.jboss.as.quickstarts.greeter.web.DeveloperController.trainmodel().
The documentation for this interface was generated from the following file:
src/main/java/org/jboss/as/quickstarts/greeter/domain/ModelDao.java